---
# tasks file for boerhaave.exhibit

    #- name: Register teamviewer ID
    #  shell: teamviewer info | grep 'TeamViewer ID' | awk '{print $5}'
    #  register: teamviewer_id
    #    
    #- name: mansveld config
    #  include: mansveld.yaml
    #
    #- name: Gnome Settings
    #  include: gsettings.yaml
    #
    #- name: User config / Auto Login / Etc
    #  include: user_config.yaml
    #
    #- name: Configure App
    #  include: nodejs_app.yaml
    #  when: not remove_app and
    #        deploy_app
    #
    #- name: remove app
    #  include: remove_app.yaml
    #  when: remove_app
    #
    #- name: set sound settings
    #  include: volume.yaml

- name: reboot system 
  shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  register: reboot_required

- name: waiting for server to come back
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay=10 timeout=220 port=22
  become: false
  when: reboot_required.changed

- name: verify a reboot was actually initiated
  # machine should have started after it has been rebooted
  shell: echo rebooted
  become: false
  when: reboot_required.changed

