---
# handlers file for boerhaave.exhibit

- name: reboot sequence
  changed_when: "true"
  debug: msg='trigger machine reboot sequence'
  notify:
    - reboot system
    - waiting for server to come back
    - verify a reboot was actually initiated

- name: reboot system
  shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ ansible_host }} state=started delay=10 timeout=220 port=22
  become: false

- name: verify a reboot was actually initiated
  # machine should have started after it has been rebooted
  shell: echo rebooted
  become: false

- name: restart docker app
  shell: docker restart app
  become: false
